# Generated by Django 4.2.6 on 2023-10-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='employee',
            field=models.CharField(max_length=30),
        ),
    ]
